app:
  base-url: https://api.recipit.com #임의의 url

cors:
  allowed-origins:
    http://localhost:8081,
    http://localhost:3000

spring:
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5