app:
  base-url: http://localhost:8080

cors:
  allowed-origins:
    http://localhost:8081

spring:
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3

server:
  servlet:
    session:
      cookie:
        same-site: Lax