spring:
  application:
    name: Recipit
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 550MB
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml

imagekit:
  publicKey: ${IMAGEKIT_PUBLIC_KEY}
  privateKey: ${IMAGEKIT_PRIVATE_KEY}
  urlEndpoint: ${IMAGEKIT_URL_ENDPOINT}
  defaultExpireTime: 60

logging:
  level:
    org.mybatis: DEBUG

jasypt:
  password: ${JASYPT_PASSWORD}

internal:
  auth-key: ${INTERNAL_AUTH_KEY}

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        same-site: none