app:
  base-url: http://localhost:8080

cors:
  allowed-origins:
    -http://localhost:8081
    -https://scdev4--recipit-api--qj5x98zdln7d.code.run/

spring:
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3