app:
  base-url: https://scdev4--recipit-api--qj5x98zdln7d.code.run #임의의 url

cors:
  allowed-origins:
    http://localhost:8081,
    http://localhost:3000

spring:
  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5